import pandas as pd
import os
from current_dir import get_current_dir

BASE_DIR = get_current_dir()
data_path = os.path.join(BASE_DIR, "..", "data")
data_path = os.path.normpath(data_path)

df = pd.read_csv(os.path.join(data_path, "Sample_Superstore.csv"), encoding="latin1")
print(df[["Order Date", "Sales", "Region", "Category"]].isnull().sum())
print(df.isnull().sum())
print(df[df["Order Date"].isnull()])
print(df[df["Sales"].isnull()])
print(df[df["Region"].isnull()])
print(df[df["Category"].isnull()])
print(df[df["Sub-Category"].isnull()])
print(df[df["Product Name"].isnull()])
print(df[df["Product ID"].isnull()])
print(df[df["Customer ID"].isnull()])
print(df[df["Ship Mode"].isnull()])
print(df[df["Ship Date"].isnull()])
print(df[df.duplicated()])
print(df[df.duplicated(subset=["Row ID"])])
print(df[df.duplicated(subset=["Order ID"])])
df = df.drop_duplicates()
df = df.drop_duplicates(subset=["Row ID"])
df = df.dropna(subset=["Order Date", "Sales"])
df["Region"] = df["Region"].fillna("Unknown")
df["Category"] = df["Category"].fillna("Unknown")
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])
df["Sales"] = df["Sales"].astype(float)
df["Profit"] = df["Profit"].astype(float)
df["Quantity"] = df["Quantity"].astype(int)
df["Discount"] = df["Discount"].astype(float)
df.to_csv(os.path.join(data_path, "superstore_cleaned.csv"), index=False)